name: "Mihoyo SignIn"

on:
  workflow_dispatch:
  schedule:
    - cron: "32 05 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install packages 
        run: npm install
      - name: run sign
        run: node index.js > log.txt
        env:
          COOKIE_STRING: ${{secrets.COOKIE_STRING}}

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.126.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME_SEND }}
          password: ${{ secrets.MAIL_PASSWORD_SEND }}
          subject: miho
          body: file://log.txt
          to: ${{ secrets.MAIL_USERNAME_GET }}
          from: My 126 mail
          content_type: text/html
