name: "Mihoyo SignIn"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install packages 
        run: npm install
      - name: run sign
        run: node dist/main.js
        env:
          COOKIE_STRING: ${{secrets.COOKIE_STRING}}
          QY_WECHAT: ${{secrets.QY_WECHAT}}
      - uses: actions/upload-artifact@v2
        with:
          name: mihoyo-log
          path: log/mihoyo.log
